skip_welcome_message = true
prompt = "echo $(starship prompt)"
startup = [
    "alias d = docker",
    "alias dc = docker-compose",
    "alias g = git",
    "alias k = kubectl",
    "alias tf = terraform",
    "def glg [n] { git log --pretty=%h»¦«%aN»¦«%s»¦«%ar | lines | split column \"»¦«\" hash committer subject time | first $n }",
    "def killit [p] { ps | where name =~ $p | get pid | each { kill --force $it } }",
]
